name: Build on PR
on:
    pull_request:
        branches:
            -main
    

jobs:
    build:
        name: Builds the application
        runs-on: ubuntu-latest
        steps:
            - name: Cloning the repo
              uses: actions/checkout@v3
            - name: Installing Nodejs
              uses: actions/setup-node@v3
              with: 
                node-version: '20'
            - name: Install Dependencies
              run: npm install
            - name: Generating Prisma Client
              run: npm run db:generate
            - name: Run Build
              run: npm run build

