name: Build and push to Docker hub
on:
    push:
        branches:
            -main

jobs:
    build-and-push:
        name: Builds and publishes image on DockerHub
        runs-on: ubuntu-latest
        steps:
            - name: Clone the repo
              uses: actions/checkout@v3
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with: 
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Build and push the image
              uses: docker/build-push-action@v2
              with:
                context: .
                file: ./docker/Dockerfile.user
                push: true
                tags: adityapandey51/baypay:latest

            - name: verify pushed image
              run: docker pull adityapandey51/baypay:latest 
